export * from './IgraTokenPage'
export * from './BenefitsPage'
export * from './BenefitsPage2'
export * from './EcosystemPage'
export * from './HeroPage'
export * from './ManifestoPage'
export { default as PrivacyPage } from './PrivacyPage'
export { default as TermsPage } from './TermsPage'
export * from './TeamPage'
export * from './VisionPage'
export * from './NewsPage'
